### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ZEROX7** [cyanog3n/experienceobelisk-1.18#3]
[crash-2022-10-23_11.28.56-fml.txt](https://github.com/cyanog3n/experienceobelisk-1.18/files/9846277/crash-2022-10-23_11.28.56-fml.txt)

**Comment by cyanog3n** [comment]
I'm sorry but... why are you submitting this here exactly? The stacktrace doesn't seem point to my mod as the issue

**Comment by ZEROX7** [comment]
[crash-2022-10-23_21.27.34-fml.txt](https://github.com/cyanog3n/experienceobelisk-1.18/files/9851766/crash-2022-10-23_21.27.34-fml.txt)
